-- ============================================================================
--  bootstrap_admin_seed.sql  -  GENERATED by scripts/build_bootstrap_sql.cjs.
--  Creates ONE account + admin user + workspace so you can log in. Run AFTER
--  bootstrap_schema.sql (plans are already seeded by 02_accounts_auth.sql).
--
--  DEFAULT LOGIN:   admin@example.com   /   Password123!
--  >>> Edit the email below before running, and change the password in the UI
--      right after your first login. The hash below is bcrypt of the password
--      above; to set a different password without the app, regenerate the hash.
-- ============================================================================
WITH acct AS (
  INSERT INTO app.accounts (name, slug, plan)
  VALUES ('My Company', 'my-company', 'standard')
  RETURNING id
),
usr AS (
  INSERT INTO app.users (account_id, email, password_hash, full_name,
                         is_email_verified, is_active, is_platform_admin)
  SELECT id, 'admin@example.com', '$2b$10$LVkpTYduo2wLGPI2PzjNmeFGfH2Ur3VfXmUg7CG9PkUKHFaZAsl1m', 'Admin', true, true, true
  FROM acct
  RETURNING id, account_id
),
comp AS (
  INSERT INTO app.companies (account_id, name, slug, capsuite_ref, plan, is_active)
  SELECT account_id, 'My Workspace', 'my-workspace', 'my_workspace', 'standard', true
  FROM usr
  RETURNING id, account_id
),
mem AS (
  INSERT INTO app.company_members (account_id, company_id, user_id, role, status)
  SELECT c.account_id, c.id, u.id, 'admin', 'active'
  FROM comp c, usr u
  RETURNING id
)
UPDATE app.accounts a SET owner_user_id = u.id FROM usr u WHERE a.id = u.account_id;
