-- 2026-07-02  Hard-enforce the per-account AI token limit.  [SUPERSEDED - NO-OP]
-- ---------------------------------------------------------------------------
-- This migration originally created app.ai_quota(UUID) returning
--   (used, token_limit, is_over)  -- calendar-month window.
--
-- It has been fully SUPERSEDED by 2026-07-02_ai_quota_billing_period.sql, which
-- redefines app.ai_quota(UUID) with an expanded return type
--   (used, token_limit, is_over, period_start, period_end, is_trial)
-- over the account's BILLING PERIOD instead of the calendar month.
--
-- Migrations are re-applied in filename order on every deploy and must all be
-- idempotent. "billing_period" sorts BEFORE "enforcement", so billing_period
-- creates the 6-column function first; this file then ran afterwards and tried
-- to CREATE OR REPLACE it back to the 3-column signature, which Postgres rejects
-- ("cannot change return type of existing function") and broke the deploy.
--
-- The original body is therefore removed and this file is intentionally a no-op.
-- Do NOT re-add a CREATE/REPLACE of app.ai_quota here; own its definition in
-- 2026-07-02_ai_quota_billing_period.sql (or a later dated migration).
--   Run with: psql "$DATABASE_URL" -f <file>

SELECT 1;  -- no-op; superseded by 2026-07-02_ai_quota_billing_period.sql
