#!/usr/bin/env node
/* ============================================================================
 *  build_bootstrap_sql.cjs - generate two ready-to-run .sql files for setting
 *  up a NEW database WITHOUT node access on the server (e.g. Render free tier):
 *
 *    server/sql/bootstrap_schema.sql     drop + base 01..NN + migrations
 *    server/sql/bootstrap_admin_seed.sql one account + admin user + workspace
 *
 *  Paste/run each against the DB's EXTERNAL connection URL in any SQL client.
 *  Re-run this generator whenever the SQL files change. Run:
 *    node scripts/build_bootstrap_sql.cjs
 * ========================================================================== */
const fs = require("fs");
const path = require("path");
const bcrypt = require("bcryptjs");

const SQL = path.join(__dirname, "..", "server", "sql");
const MIG = path.join(SQL, "migrations");

const base = fs.readdirSync(SQL)
  .filter((f) => /^\d\d_.*\.sql$/.test(f) && !f.startsWith("00_"))
  .sort();
// The numbered base files (01..NN) are the complete source of truth for a fresh
// database - every migration's final state has been folded back into them. The
// dated files under migrations/ are OPTIONAL idempotent catch-ups for upgrading
// pre-existing databases; a fresh build does not need them. So tolerate the
// folder being emptied or removed entirely.
const migs = fs.existsSync(MIG)
  ? fs.readdirSync(MIG).filter((f) => f.endsWith(".sql")).sort()
  : [];

// ── 1. consolidated schema ──────────────────────────────────────────────────
const header = `-- ============================================================================
--  bootstrap_schema.sql  -  GENERATED by scripts/build_bootstrap_sql.cjs.
--  Full schema build for a NEW/empty database, runnable directly in any SQL
--  client (psql, TablePlus, DBeaver, pgAdmin, the Render dashboard query box).
--  Run the WHOLE file at once - it contains dollar-quoted ($$) function bodies,
--  so do NOT split it statement-by-statement on semicolons.
--  DESTRUCTIVE: drops and recreates all app schemas first.
--  Order: drop -> base ${base[0]}..${base[base.length - 1]} -> migrations.
--  Afterwards run bootstrap_admin_seed.sql to create your login.
-- ============================================================================
DROP SCHEMA IF EXISTS app         CASCADE;
DROP SCHEMA IF EXISTS manual      CASCADE;
DROP SCHEMA IF EXISTS ga_landing  CASCADE;
DROP SCHEMA IF EXISTS shopify     CASCADE;
DROP SCHEMA IF EXISTS shopline    CASCADE;
DROP SCHEMA IF EXISTS odoo        CASCADE;
DROP SCHEMA IF EXISTS commerce    CASCADE;
DROP SCHEMA IF EXISTS interaction CASCADE;
DROP SCHEMA IF EXISTS public      CASCADE;
CREATE SCHEMA public;
`;

const parts = [header];
for (const f of base) {
  parts.push(`\n-- ========================= ${f} =========================\n`);
  parts.push(fs.readFileSync(path.join(SQL, f), "utf8"));
}
if (migs.length) {
  parts.push("\n\n-- ######################### MIGRATIONS (idempotent catch-ups; base files above are already complete) #########################\n");
  for (const f of migs) {
    parts.push(`\n-- ===================== migrations/${f} =====================\n`);
    parts.push(fs.readFileSync(path.join(MIG, f), "utf8"));
  }
}
fs.writeFileSync(path.join(SQL, "bootstrap_schema.sql"), parts.join("\n"));
console.log(`wrote server/sql/bootstrap_schema.sql  (${base.length} base + ${migs.length} migrations)`);

// ── 2. admin seed (real bcrypt hash so login works with no node on the server) ─
const EMAIL = "admin@example.com";
const PASSWORD = "Password123!";
const hash = bcrypt.hashSync(PASSWORD, 10);

const seed = `-- ============================================================================
--  bootstrap_admin_seed.sql  -  GENERATED by scripts/build_bootstrap_sql.cjs.
--  Creates ONE account + admin user + workspace so you can log in. Run AFTER
--  bootstrap_schema.sql (plans are already seeded by 02_accounts_auth.sql).
--
--  DEFAULT LOGIN:   ${EMAIL}   /   ${PASSWORD}
--  >>> Edit the email below before running, and change the password in the UI
--      right after your first login. The hash below is bcrypt of the password
--      above; to set a different password without the app, regenerate the hash.
-- ============================================================================
WITH acct AS (
  INSERT INTO app.accounts (name, slug, plan)
  VALUES ('My Company', 'my-company', 'standard')
  RETURNING id
),
usr AS (
  INSERT INTO app.users (account_id, email, password_hash, full_name,
                         is_email_verified, is_active, is_platform_admin)
  SELECT id, '${EMAIL}', '${hash}', 'Admin', true, true, true
  FROM acct
  RETURNING id, account_id
),
comp AS (
  INSERT INTO app.companies (account_id, name, slug, capsuite_ref, plan, is_active)
  SELECT account_id, 'My Workspace', 'my-workspace', 'my_workspace', 'standard', true
  FROM usr
  RETURNING id, account_id
),
mem AS (
  INSERT INTO app.company_members (account_id, company_id, user_id, role, status)
  SELECT c.account_id, c.id, u.id, 'admin', 'active'
  FROM comp c, usr u
  RETURNING id
)
UPDATE app.accounts a SET owner_user_id = u.id FROM usr u WHERE a.id = u.account_id;
`;
fs.writeFileSync(path.join(SQL, "bootstrap_admin_seed.sql"), seed);
console.log(`wrote server/sql/bootstrap_admin_seed.sql  (login ${EMAIL} / ${PASSWORD})`);
